initial commit

diff --git a/devops/Makefile b/devops/Makefile
--- a/devops/Makefile
+++ b/devops/Makefile
@@ -328,24 +328,24 @@ deploy-migrations:
 run-db-migrations:
 	test -n "$(NAMESPACE)"
 	test -n "$(BUILD_REF)"
-	test -n "$(DB_MIGRATIONS_JOB_NAME)"
+	test -n "$(MIGRATIONS_JOB_NAME)"
 	@echo "+\n++ Run DB_MIGRATIONS with tag: $(BUILD_REF)\n+"
-	@oc -n $(NAMESPACE) exec job/$(DB_MIGRATIONS_JOB_NAME) -- npm run migration:run
+	@oc -n $(NAMESPACE) exec job/$(MIGRATIONS_JOB_NAME) -- npm run migration:run
 
 deploy-form-definitions:
 	test -n "$(NAMESPACE)"
 	test -n "$(BUILD_REF)"
-	test -n "$(DB_MIGRATIONS_JOB_NAME)"
+	test -n "$(MIGRATIONS_JOB_NAME)"
 	@echo "+\n++ Run DB_MIGRATIONS with tag: $(BUILD_REF)\n+"
-	@oc -n $(NAMESPACE) exec job/$(DB_MIGRATIONS_JOB_NAME) -- npm run deploy --prefix forms
+	@oc -n $(NAMESPACE) exec job/$(MIGRATIONS_JOB_NAME) -- npm run deploy --prefix forms
 
 wait-for-db-migrations:
-	while [ "$$(oc -n $(NAMESPACE) get job $(DB_MIGRATIONS_JOB_NAME) -o=jsonpath='{.status.conditions[?(@.type=="Complete")].status}' || echo "None")" != "True" ] && [ "$$WAIT_TIME" -lt "$$MAX_WAIT" ]; do sleep 5; WAIT_TIME=$$((WAIT_TIME+5)); done
-	if [ "$$(oc -n $(NAMESPACE) get job $(DB_MIGRATIONS_JOB_NAME) -o=jsonpath='{.status.conditions[?(@.type=="Complete")].status}' || echo "None")" != "True" ]; then echo "Error: Job $(DB_MIGRATIONS_JOB_NAME) failed to complete within the specified timeout"; exit 1; fi
+	while [ "$$(oc -n $(NAMESPACE) get job $(MIGRATIONS_JOB_NAME) -o=jsonpath='{.status.conditions[?(@.type=="Complete")].status}' || echo "None")" != "True" ] && [ "$$WAIT_TIME" -lt "$$MAX_WAIT" ]; do sleep 5; WAIT_TIME=$$((WAIT_TIME+5)); done
+	if [ "$$(oc -n $(NAMESPACE) get job $(MIGRATIONS_JOB_NAME) -o=jsonpath='{.status.conditions[?(@.type=="Complete")].status}' || echo "None")" != "True" ]; then echo "Error: Job $(MIGRATIONS_JOB_NAME) failed to complete within the specified timeout"; exit 1; fi
 
 delete-db-migrations:
-	@if [ -n "$(shell oc -n $(NAMESPACE) get job $(DB_MIGRATIONS_JOB_NAME) -o name 2>/dev/null)" ]; then \
-		oc -n $(NAMESPACE) delete job $(DB_MIGRATIONS_JOB_NAME); \
+	@if [ -n "$(shell oc -n $(NAMESPACE) get job $(MIGRATIONS_JOB_NAME) -o name 2>/dev/null)" ]; then \
+		oc -n $(NAMESPACE) delete job $(MIGRATIONS_JOB_NAME); \
 			echo "Job deleted."; \
 	else \
 		echo "Job not found."; \
