#6438 - Release 4.1.0 - Sonar Cloud Warnings (#6465)
Resolving some of the SonarCloud issues related to security and/or
blocker severity.

- [inputs.clamavImageTag is vulnerable to script
injection](https://sonarcloud.io/project/issues?open=AZlyYoGwn9FuR2p_kPxL&id=bcgov_SIMS)
- [inputs.restore_target is vulnerable to script
injection](https://sonarcloud.io/project/issues?open=AZlyYoGon9FuR2p_kPxF&id=bcgov_SIMS)
- [Omitting "--ignore-scripts" allows lifecycle scripts to run during
package
installation](https://sonarcloud.io/project/issues?open=AZ-BKpo5wtmLxaBBkOFw&id=bcgov_SIMS)
- [Complete this assertion; 'expect' doesn't assert anything by
itself](https://sonarcloud.io/project/issues?open=AZ7xTs-PXFDWlQGUVcPd&id=bcgov_SIMS)

_Note:_ The [@suites/unit](https://www.npmjs.com/package/@suites/unit)
has a `postinstall` script that was affected by `--ignore-scripts` in
`npm ci`. The `docker.dev` was adjusted to allow the `postinstall`
script to run only for this package.

---------

Co-authored-by: Copilot Autofix powered by AI <175728472+Copilot@users.noreply.github.com>

diff --git a/.github/workflows/clamav.yml b/.github/workflows/clamav.yml
--- a/.github/workflows/clamav.yml
+++ b/.github/workflows/clamav.yml
@@ -44,5 +44,13 @@ jobs:
           oc login --token=${{ secrets.SA_TOKEN }} --server=${{ vars.OPENSHIFT_CLUSTER_URL }}
       - name: Manage ClamAV
         working-directory: "./devops/helm/clam-av/main/"
+        env:
+          ACTION: ${{ inputs.action }}
+          NAMESPACE: ${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
+          IMAGE_TAG: ${{ inputs.clamavImageTag }}
         run: |
-          make ${{ inputs.action }} NAMESPACE=${{ secrets.OPENSHIFT_ENV_NAMESPACE }} IMAGE_TAG=${{ inputs.clamavImageTag }}
+          if [[ ! "$IMAGE_TAG" =~ ^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$ ]]; then
+            echo "Error: IMAGE_TAG must be a valid OCI image tag."
+            exit 1
+          fi
+          make "$ACTION" NAMESPACE="$NAMESPACE" IMAGE_TAG="$IMAGE_TAG"
