parameterized

diff --git a/.github/workflows/crunchy-db.yml b/.github/workflows/crunchy-db.yml
--- a/.github/workflows/crunchy-db.yml
+++ b/.github/workflows/crunchy-db.yml
@@ -1,5 +1,5 @@
 name: Crunchy DB - Install/Upgrade
-run-name: Crunchy DB -  ${{ inputs.environment }} Crunchy DB in ${{ inputs.environment }} using ${{ github.ref_name }}
+run-name: Crunchy DB - ${{ inputs.environment }} Crunchy DB in ${{ inputs.environment }} using ${{ github.ref_name }}
 
 on:
   workflow_dispatch:
@@ -15,6 +15,18 @@ on:
         options:
           - install
           - upgrade
+      restore_enabled:
+        description: "Enable restore"
+        required: true
+        type: choice
+        options:
+          - "true"
+          - "false"
+      restore_target:
+        description: "Restore target date and time in 'YYYY-MM-DD HH:MM:SS'format "
+        required: false
+        type: string
+        default: ""
 
 jobs:
   manageCrunchyDB:
@@ -31,7 +43,17 @@ jobs:
       - name: Log in to OpenShift
         run: |
           oc login --token=${{ secrets.SA_TOKEN }} --server=${{ vars.OPENSHIFT_CLUSTER_URL }}
+
+      - name: Validate Date Time Format
+        if: ${{ inputs.restore_enabled == 'true' }}
+        run: |
+          # Define the date-time format regex pattern
+          DATE_TIME_REGEX='^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
+          if ! echo "${{ inputs.restore_target }}" | grep -Pq "$DATE_TIME_REGEX"; then
+            echo "Error: RESTORE_TARGET must be in the format 'YYYY-MM-DD HH:MM:SS'."
+            exit 1
+          fi
       - name: Manage Crunchy DB
         working-directory: "./devops/helm/crunchy-postgres/"
         run: |
-          make ${{ inputs.action }} NAMESPACE=${{ secrets.OPENSHIFT_ENV_NAMESPACE }}
+          make ${{ inputs.action }} NAMESPACE=${{ secrets.OPENSHIFT_ENV_NAMESPACE }} RESTORE_ENABLED=${{ inputs.restore_enabled }} RESTORE_TARGET=${{ inputs.restore_target }}
diff --git a/devops/helm/crunchy-postgres/Makefile b/devops/helm/crunchy-postgres/Makefile
--- a/devops/helm/crunchy-postgres/Makefile
+++ b/devops/helm/crunchy-postgres/Makefile
@@ -18,8 +18,15 @@ install:
 
 .PHONY: upgrade
 upgrade: helm-dep
-upgrade:
-	@helm upgrade --install ${NAME} . -n ${NAMESPACE} -f values.yaml
+	@if [ "${RESTORE_ENABLED}" = "true" ]; then \
+		if [ -z "${RESTORE_TARGET}" ]; then \
+			echo "Error: RESTORE_TARGET is required when RESTORE_ENABLED is true."; \
+			exit 1; \
+		fi; \
+		helm upgrade --install ${NAME} . -n ${NAMESPACE} --set restore.enabled=true --set restore.options.target="${RESTORE_TARGET}" -f values.yaml; \
+	else \
+		helm upgrade --install ${NAME} . -n ${NAMESPACE} --set restore.enabled=false -f values.yaml; \
+	fi
 
 .PHONY: uninstall
 uninstall: helm-dep
